services:

  tailscale-uptime-kuma:
    image: tailscale/tailscale:v1.80.0
    container_name: tailscale-uptime-kuma
    hostname: uptime-kuma
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - "TS_EXTRA_ARGS=--advertise-tags=tag:monitoring --reset"
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=uptime-kuma
      - TS_SERVE_CONFIG=/config/serve-config.json
      - TS_ENABLE_HEALTH_CHECK=true
      - TS_LOCAL_ADDR_PORT=127.0.0.1:9002
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:9002/healthz"]
    volumes:
      - ./volumes/tailscale-uptime-kuma/state:/var/lib/tailscale
      - ./volumes/tailscale-uptime-kuma/config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16-alpine
    container_name: uptime-kuma
    volumes:
      - ./volumes/uptime-kuma/data:/app/data
    network_mode: service:tailscale-uptime-kuma
    restart: always